home:
    pattern:  /
    defaults: { _controller: MadoquaBundle:Post:index}
    
post_read:
    pattern: post/:identifier
    defaults: {_controller: MadoquaBundle:Post:read}

book_index:
    pattern: book
    defaults: {_controller: MadoquaBundle:Book:index}

book_chapter:
    pattern: book/chapter/:path
    defaults: {_controller: MadoquaBundle:Book:chapter}

book_page:
    pattern: book/page/:path
    defaults: {_controller: MadoquaBundle:Book:chapter}
